#!/usr/bin/env python3
"""
svg_to_rgb565.py
================
Generates the C header used by the Arduino sketch to display the splash logo.

Reads ../assets/logo.svg, rasterises it to a fixed-size RGB565 little-endian
bitmap on the dark background used by the hub, and writes the byte array as a
PROGMEM-friendly static array in ../Control_Hub_War_Thunder/splash_image.h.

The SVG parser supports only the primitives used by assets/logo.svg:
  <rect>, <circle>, <polygon>, simple <path d="M x,y L x,y ... Z">.
Anything more elaborate is silently ignored.

Run after editing the logo:

    python3 scripts/svg_to_rgb565.py
"""

from __future__ import annotations

import os
import re
import sys
import xml.etree.ElementTree as ET

import numpy as np
from PIL import Image, ImageDraw

REPO_ROOT  = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SVG_PATH   = os.path.join(REPO_ROOT, "assets", "logo.svg")
HEADER_OUT = os.path.join(REPO_ROOT, "Control_Hub_War_Thunder", "splash_image.h")

SPLASH_W   = 280
SPLASH_H   = 280
BG_HEX     = "#051005"


def parse_color(s: str) -> tuple[int, int, int]:
    s = (s or "").strip().lower()
    if s.startswith("#") and len(s) == 7:
        return int(s[1:3], 16), int(s[3:5], 16), int(s[5:7], 16)
    if s.startswith("#") and len(s) == 4:
        return int(s[1] * 2, 16), int(s[2] * 2, 16), int(s[3] * 2, 16)
    return 255, 255, 255


def rasterise_svg(svg_path: str, out_w: int, out_h: int, bg: str) -> Image.Image:
    tree = ET.parse(svg_path)
    root = tree.getroot()

    vb = root.attrib.get("viewBox", "0 0 48 48").split()
    vb_w = float(vb[2])
    vb_h = float(vb[3])

    side = min(out_w, out_h)
    scale = side / max(vb_w, vb_h)
    offset_x = (out_w - vb_w * scale) / 2
    offset_y = (out_h - vb_h * scale) / 2

    img = Image.new("RGB", (out_w, out_h), parse_color(bg))
    draw = ImageDraw.Draw(img, "RGBA")

    ns = "{http://www.w3.org/2000/svg}"
    for el in root.iter():
        tag = el.tag.replace(ns, "")
        fill = parse_color(el.attrib.get("fill", "#ffffff"))

        if tag == "rect":
            x = float(el.attrib["x"]) * scale + offset_x
            y = float(el.attrib["y"]) * scale + offset_y
            w = float(el.attrib["width"]) * scale
            h = float(el.attrib["height"]) * scale
            draw.rectangle([x, y, x + w, y + h], fill=fill)

        elif tag == "circle":
            cx = float(el.attrib["cx"]) * scale + offset_x
            cy = float(el.attrib["cy"]) * scale + offset_y
            r  = float(el.attrib["r"])  * scale
            draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=fill)

        elif tag == "polygon":
            pts_raw = el.attrib.get("points", "")
            pts = [
                (float(p.split(",")[0]) * scale + offset_x,
                 float(p.split(",")[1]) * scale + offset_y)
                for p in pts_raw.split()
                if "," in p
            ]
            if len(pts) >= 3:
                draw.polygon(pts, fill=fill)

        elif tag == "path":
            d = el.attrib.get("d", "")
            tokens = re.findall(r"[MLZmlz]|-?\d+(?:\.\d+)?", d)
            pts: list[tuple[float, float]] = []
            i = 0
            cur_x = cur_y = 0.0
            while i < len(tokens):
                tk = tokens[i]
                if tk in ("M", "L"):
                    cur_x = float(tokens[i + 1])
                    cur_y = float(tokens[i + 2])
                    pts.append((cur_x * scale + offset_x,
                                cur_y * scale + offset_y))
                    i += 3
                elif tk in ("m", "l"):
                    cur_x += float(tokens[i + 1])
                    cur_y += float(tokens[i + 2])
                    pts.append((cur_x * scale + offset_x,
                                cur_y * scale + offset_y))
                    i += 3
                elif tk in ("Z", "z"):
                    i += 1
                else:
                    i += 1
            if len(pts) >= 3:
                draw.polygon(pts, fill=fill)

    return img


def image_to_rgb565_le(img: Image.Image) -> bytes:
    arr = np.asarray(img.convert("RGB"), dtype=np.uint8)
    r, g, b = arr[..., 0], arr[..., 1], arr[..., 2]
    v = ((r.astype(np.uint16) >> 3) << 11) \
      | ((g.astype(np.uint16) >> 2) <<  5) \
      | ( b.astype(np.uint16) >> 3)
    out = np.empty(v.size * 2, dtype=np.uint8)
    out[0::2] = (v & 0xFF).flatten()
    out[1::2] = ((v >> 8) & 0xFF).flatten()
    return out.tobytes()


def emit_header(path: str, w: int, h: int, data: bytes) -> None:
    lines = []
    lines.append("// Auto-generated by scripts/svg_to_rgb565.py — do not edit by hand.")
    lines.append("// Source: assets/logo.svg")
    lines.append("#pragma once")
    lines.append("")
    lines.append('#include "lvgl.h"')
    lines.append("")
    lines.append(f"#define SPLASH_IMG_W  {w}")
    lines.append(f"#define SPLASH_IMG_H  {h}")
    lines.append(f"#define SPLASH_IMG_BYTES  ({w} * {h} * 2)")
    lines.append("")
    lines.append("// RGB565 little-endian pixel data, stored in flash (PROGMEM-equivalent on Mbed).")
    lines.append("static const uint8_t splash_rgb565[] __attribute__((aligned(4))) = {")
    chunk = 16
    for i in range(0, len(data), chunk):
        row = ", ".join(f"0x{b:02X}" for b in data[i:i + chunk])
        lines.append(f"    {row},")
    lines.append("};")
    lines.append("")
    lines.append("static const lv_image_dsc_t splash_dsc = {")
    lines.append("    .header = {")
    lines.append("        .magic  = LV_IMAGE_HEADER_MAGIC,")
    lines.append("        .cf     = LV_COLOR_FORMAT_RGB565,")
    lines.append("        .flags  = 0,")
    lines.append(f"        .w      = {w},")
    lines.append(f"        .h      = {h},")
    lines.append(f"        .stride = {w * 2},")
    lines.append("    },")
    lines.append(f"    .data_size = {len(data)},")
    lines.append("    .data      = splash_rgb565,")
    lines.append("};")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))


def main() -> int:
    if not os.path.exists(SVG_PATH):
        print(f"error: missing {SVG_PATH}", file=sys.stderr)
        return 1
    img = rasterise_svg(SVG_PATH, SPLASH_W, SPLASH_H, BG_HEX)
    data = image_to_rgb565_le(img)
    emit_header(HEADER_OUT, SPLASH_W, SPLASH_H, data)
    print(f"Wrote {HEADER_OUT} ({len(data)} bytes, {SPLASH_W}x{SPLASH_H})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
